/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hermeslojanetbeans.view;

/**
 *
 * @author marcos
 */
public class TelaNotaFiscal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaNotaFiscal
     */
    public TelaNotaFiscal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGerarNotaFiscal = new javax.swing.JButton();
        btEnviarNotaFiscal = new javax.swing.JButton();

        btGerarNotaFiscal.setText("Gerar Nota Fiscal");

        btEnviarNotaFiscal.setText("Enviar Nota Fiscal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(654, Short.MAX_VALUE)
                .addComponent(btGerarNotaFiscal)
                .addGap(38, 38, 38)
                .addComponent(btEnviarNotaFiscal)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGerarNotaFiscal)
                    .addComponent(btEnviarNotaFiscal))
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviarNotaFiscal;
    private javax.swing.JButton btGerarNotaFiscal;
    // End of variables declaration//GEN-END:variables
}
